"use client";
import { ChangeEvent, useRef, useState } from "react";
import { Assignment, blankConfiguration, blankPreset, Configuration, exportEditorDraft, GroupMember, LEVEL_MAX, LEVEL_NOMINAL, parseConfiguration, parseME1, writeConfiguration, writeME1 } from "./me1-format";

const inputName = (source:number, labels:string[]) => labels[source-1]?.trim() ? `IN ${source} · ${labels[source-1].trim()}` : `IN ${source}`;
const sourceName = (a: Assignment, labels:string[]) => a.kind === "input" ? inputName(a.source,labels) : a.kind === "group" ? `GRP ${a.members.length}` : a.kind === "signal" ? "SIG GEN" : a.kind.toUpperCase();
const saveBlob = (blob: Blob, name: string) => { const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); };

const safePresetName = (name: string) => name.toUpperCase().replace(/[^A-Z0-9_]/g, "").slice(0, 8);
const copyPreset = (preset: ReturnType<typeof blankPreset>) => ({ ...preset, assignments: JSON.parse(JSON.stringify(preset.assignments)), keyNames: JSON.parse(JSON.stringify(preset.keyNames)), sourceFile: preset.sourceFile && { ...preset.sourceFile, bytes: preset.sourceFile.bytes.slice() }, original: preset.original && JSON.parse(JSON.stringify(preset.original)) });
const emptySourceNames = () => Array.from({length:40},()=>"");
const sourceNamesFile = (name:string,labels:string[]) => new Blob([JSON.stringify({schema:"me1-editor-source-names/v1",name,sources:labels},null,2)],{type:"application/json"});

export function ME1Editor() {
  const [preset, setPreset] = useState(blankPreset); const [configuration, setConfiguration] = useState<Configuration | null>(null); const [configSlot, setConfigSlot] = useState(1); const [editorMode, setEditorMode] = useState<"config"|"mix">("mix"); const [sourceNamesOpen,setSourceNamesOpen] = useState(false); const [sourceSetName,setSourceSetName] = useState("SOURCE NAMES"); const [sourceLabels,setSourceLabels] = useState(emptySourceNames); const [selected, setSelected] = useState(0); const [memberSource, setMemberSource] = useState(1); const [groupView, setGroupView] = useState(false); const [notice, setNotice] = useState("New preset ready · built from the hardware-validated template"); const fileRef = useRef<HTMLInputElement>(null); const sourceFileRef=useRef<HTMLInputElement>(null);
  const assignment = preset.assignments[selected]; const keyName = preset.keyNames[selected];
  const members = assignment.kind === "group" ? assignment.members : []; const memberSet = new Set(members.map(m => m.source)); const activeMember = assignment.kind === "group" ? assignment.members.find(m => m.source === memberSource) : undefined;
  const displayName = keyName.mode === "custom" && keyName.customName ? keyName.customName : sourceName(assignment,sourceLabels);
  const selectKey = (key:number) => { setSelected(key); setGroupView(false); };
  const replace = (next: Assignment) => setPreset(p => ({ ...p, assignments: p.assignments.map((a,i) => i === selected ? next : a) }));
  const updateMix = (values: Partial<Pick<Assignment,"level"|"pan"|"muted">>) => replace({ ...assignment, ...values } as Assignment);
  const rename = (mode:"console"|"custom", customName=keyName.customName) => setPreset(p => ({ ...p, keyNames:p.keyNames.map((n,i)=>i===selected?{mode,customName}:n) }));
  const makeGroup = () => { if (assignment.kind === "group") return; const used = new Set(preset.assignments.flatMap((item,index) => item.kind === "group" ? [preset.keyNames[index].customName.match(/^grp(\d+)$/i)?.[1]] : []).filter(Boolean)); let groupNumber=1; while(used.has(String(groupNumber))) groupNumber++; setPreset(p=>({ ...p, assignments:p.assignments.map((item,index)=>index===selected?{kind:"group",members:[],level:assignment.level,pan:0,muted:assignment.muted}:item), keyNames:p.keyNames.map((item,index)=>index===selected?{mode:"custom",customName:`Grp${groupNumber}`}:item) })); };
  const updateMember = (source:number, patch:Partial<GroupMember>) => { if (assignment.kind !== "group") return; const exists = assignment.members.find(m=>m.source===source); const member={source,level:LEVEL_NOMINAL,pan:0,...exists,...patch}; replace({...assignment,members:[...assignment.members.filter(m=>m.source!==source),member].sort((a,b)=>a.source-b.source)}); setMemberSource(source); };
  const removeMember = () => { if (assignment.kind === "group") replace({...assignment,members:assignment.members.filter(m=>m.source!==memberSource)}); };
  const importSourceNames = async (e:ChangeEvent<HTMLInputElement>) => { const file=e.target.files?.[0]; if(!file)return; try { const value=JSON.parse(await file.text()) as {schema?:string;name?:string;sources?:unknown}; if(value.schema!=="me1-editor-source-names/v1"||!Array.isArray(value.sources)) throw new Error("That is not a ME-1 Editor Source Name Set."); setSourceSetName(typeof value.name==="string"?value.name.slice(0,32):"SOURCE NAMES"); setSourceLabels(Array.from({length:40},(_,index)=>typeof value.sources?.[index]==="string"?value.sources[index].slice(0,48):"")); setNotice(`${file.name} loaded · ${value.sources.filter(item=>typeof item==="string"&&item.trim()).length} inputs named`); } catch(err){setNotice(err instanceof Error?err.message:"Could not read source names.");} e.target.value=""; };
  const importFile = async (e:ChangeEvent<HTMLInputElement>) => { const file=e.target.files?.[0]; if(!file)return; try { const bytes=new Uint8Array(await file.arrayBuffer()); if(bytes.byteLength===73728){ const parsed=parseConfiguration(file.name,bytes); setConfiguration(parsed); setPreset(parsed.current); setConfigSlot(1); setEditorMode("config"); setNotice(`${file.name} decoded · Preset 1 plus ${parsed.slots.filter(Boolean).length} additional presets loaded`); } else { const parsed=parseME1(file.name,bytes); setConfiguration(null); setEditorMode("mix"); setPreset(parsed); setNotice(`${file.name} decoded · preset`); } setSelected(0); } catch(err){setNotice(err instanceof Error?err.message:"Could not read that file.");} e.target.value=""; };
  const newPreset = () => { setConfiguration(null); setEditorMode("mix"); setPreset(blankPreset()); setSelected(0); setMemberSource(1); setGroupView(false); setNotice("New preset ready · choose a name and build your mix"); };
  const newConfiguration = () => { const next=blankConfiguration(); setConfiguration(next); setEditorMode("config"); setPreset(next.current); setConfigSlot(1); setSelected(0); setMemberSource(1); setGroupView(false); setNotice("New configuration ready · build Preset 1 or choose another preset"); };
  const exportPreset = () => { try { const name=safePresetName(preset.name)||"PRESET"; const fileName=`${name}.ME1`; const bytes=writeME1({...preset,name}); saveBlob(new Blob([bytes],{type:"application/octet-stream"}),fileName); setNotice(`${fileName} exported · ready for the ME1 USB helper`); } catch(err){setNotice(err instanceof Error?err.message:"Could not export.");} };
  const saveToConfigSlot = () => { if(!configuration)return; const name=safePresetName(preset.name)||`P${configSlot}`; const next=copyPreset({...preset,name}); setConfiguration(c=>{ if(!c)return c; return configSlot===1?{...c,name, current:next}:{...c,slots:c.slots.map((slot,index)=>index===configSlot-2?next:slot)}; }); setNotice(`${name} saved as Preset ${configSlot}`); };
  const editConfigSlot = (presetNumber:number) => { if(!configuration)return; const slot=presetNumber===1?configuration.current:configuration.slots[presetNumber-2]; const next=slot?copyPreset(slot):{...blankPreset(),name:`P${presetNumber}`}; setConfigSlot(presetNumber); setPreset(next); setEditorMode("mix"); setSelected(0); setMemberSource(1); setGroupView(false); setNotice(slot?`Editing Preset ${presetNumber}: ${slot.name}`:`Building Preset ${presetNumber}`); };
  const saveAndReturnToConfig = () => { saveToConfigSlot(); setEditorMode("config"); };
  const exportConfiguration = () => { if(!configuration)return; try { const name=safePresetName(configuration.exportName)||"CONFIG"; const bytes=writeConfiguration(configuration); saveBlob(new Blob([bytes],{type:"application/octet-stream"}),`${name}.ME1`); setNotice(`${name}.ME1 exported · complete 72 KB configuration with Presets 1–16`); } catch(err){setNotice(err instanceof Error?err.message:"Could not export configuration.");} };

  return <main><header className="topbar"><div className="brand"><span className="brand-mark">ME</span><span>PRESET LAB</span></div><div className="file-actions"><input ref={fileRef} type="file" accept=".me1" onChange={importFile} hidden/><input ref={sourceFileRef} type="file" accept=".json" onChange={importSourceNames} hidden/><button className="ghost" onClick={()=>fileRef.current?.click()}>OPEN .ME1</button><button className="ghost" onClick={newPreset}>NEW MIX</button><button className="ghost" onClick={newConfiguration}>NEW CONFIG</button>{configuration?<button className="primary" onClick={exportConfiguration}>EXPORT CONFIG</button>:<button className="primary" onClick={exportPreset}>EXPORT .ME1</button>}</div></header>
    <section className="workspace"><div className="intro"><div><p className="eyebrow">ALLEN &amp; HEATH ME-1</p><h1>Your mixer,<br/>mapped simply.</h1></div><div className="status"><span className="dot"/><span>{notice}</span></div></div><div className="editor-grid">
      <section className="mixer" aria-label="Simplified ME-1 personal mixer"><div className="mixer-top"><div className="knob-block display-only"><span>LOCAL MIC</span><div className="knob small"><i/></div></div><div className="display-block"><div className="device-brand"><b>ALLEN&amp;HEATH</b><span>ME 1</span></div><DeviceScreen assignment={assignment} displayName={displayName} selected={selected} groupView={groupView} sourceLabels={sourceLabels}/></div><div className="knob-block display-only"><span>MASTER LEVEL</span><div className="knob small"><i/></div></div></div>
      <div className="hardware-controls"><div className="hardware-left"><button className="face-button round display-only" disabled>SHIFT</button><button className="face-button display-only recall-button" disabled>RECALL</button></div><div className="hardware-center"><span className="face-rule">MENU</span><div><button className={`face-button display-only ${assignment.kind==="group"?"group-lit":""}`} disabled>GROUP</button><button className="face-button display-only" disabled>SOLO</button><button className={`face-button mute-face display-only ${assignment.muted?"lit":""}`} disabled>MUTE</button></div></div><div className="hardware-right"><div className="master-control"><span>EXIT MENU</span><button className="face-button display-only" disabled>MASTER</button></div><div className="encoder-block display-only"><div className="knob encoder"><i/></div><b>LEVEL / PAN</b></div></div></div><div className="select-bank"><div className="select-row">{preset.assignments.slice(0,8).map((item,i)=><MixerKey key={i} index={i} item={item} labels={sourceLabels} selected={selected} onSelect={selectKey}/>)}</div><div className="scribble"><span>{String(selected+1).padStart(2,"0")}</span><strong>{displayName}</strong></div><div className="select-row">{preset.assignments.slice(8,16).map((item,i)=><MixerKey key={i+8} index={i+8} item={item} labels={sourceLabels} selected={selected} onSelect={selectKey}/>)}</div></div></section>
      <aside className="inspector">{sourceNamesOpen ? <SourceNamesEditor name={sourceSetName} labels={sourceLabels} onNameChange={setSourceSetName} onLabelsChange={setSourceLabels} onImport={()=>sourceFileRef.current?.click()} onExport={()=>saveBlob(sourceNamesFile(sourceSetName,sourceLabels),`${safePresetName(sourceSetName)||"SOURCE_NAMES"}.me1sources.json`)} onBack={()=>setSourceNamesOpen(false)}/> : configuration&&editorMode==="config" ? <ConfigurationManager configuration={configuration} onPresetOneNameChange={name=>setConfiguration(c=>{if(!c)return c; const next=safePresetName(name); return {...c,name:next,current:{...c.current,name:next}}})} onExportNameChange={name=>setConfiguration(c=>c?{...c,exportName:safePresetName(name)}:c)} onEditSlot={editConfigSlot} onSourceNames={()=>setSourceNamesOpen(true)} sourceCount={sourceLabels.filter(label=>label.trim()).length}/> : <><div className="inspector-title"><div><p className="eyebrow">EDITING KEY</p><h2>{String(selected+1).padStart(2,"0")}</h2></div><div className="inspector-actions"><button className="active-pill" onClick={()=>setSourceNamesOpen(true)}>SOURCE NAMES</button><span className="active-pill">{configuration?`PRESET ${configSlot}`:preset.formatStatus==="decoded-me1"?"IMPORTED":"NEW"}</span></div></div>
        {configuration&&<div className="slot-edit-banner"><div><span className="field-label">Configuration mix</span><strong>Editing Preset {configSlot}</strong></div><div><button className="ghost" onClick={()=>setEditorMode("config")}>DISCARD</button><button className="primary" onClick={saveAndReturnToConfig}>SAVE &amp; RETURN</button></div></div>}
        <label htmlFor="preset-name">{configuration?`Preset ${configSlot} name`:"Preset file name"}</label><div className="preset-name"><input id="preset-name" aria-label="Preset filename" maxLength={8} value={preset.name} placeholder="PRESET" onChange={e=>{const name=safePresetName(e.target.value); setPreset(p=>({...p,name})); if(configuration&&configSlot===1)setConfiguration(c=>c?{...c,name,current:{...c.current,name}}:c);}}/><span>{preset.name.length}/8</span></div><p className="name-help">{configuration?(configSlot===1?"Preset 1 is also the ME-1 configuration name.":"This name appears in the ME-1 recall list."):`Letters, numbers, and underscores only · exports as ${(safePresetName(preset.name)||"PRESET")}.ME1`}</p>
        <span className="field-label">Button name</span><div className="segmented name-mode"><button className={keyName.mode==="console"?"chosen":""} onClick={()=>rename("console")}>CONSOLE</button><button className={keyName.mode==="custom"?"chosen":""} onClick={()=>rename("custom")}>CUSTOM</button></div>{keyName.mode==="custom"&&<div className="custom-name"><input aria-label="Custom button name" maxLength={6} value={keyName.customName} placeholder="6 CHARS" onChange={e=>rename("custom",e.target.value.replace(/[^0-9A-Za-z ]/g,"").slice(0,6))}/><span>{keyName.customName.length}/6</span></div>}
        <span className="field-label">What this key controls</span><div className="segmented assignment-types"><button className={assignment.kind==="input"?"chosen":""} onClick={()=>replace({kind:"input",source:selected+1,level:assignment.level,pan:assignment.pan,muted:assignment.muted})}>INPUT</button><button className={assignment.kind==="group"?"chosen":""} onClick={makeGroup}>GROUP</button><button className={assignment.kind==="auto"?"chosen":""} onClick={()=>replace({kind:"auto",level:assignment.level,pan:assignment.pan,muted:assignment.muted})}>AUTO</button><button className={assignment.kind==="aux"?"chosen":""} onClick={()=>replace({kind:"aux",level:assignment.level,pan:assignment.pan,muted:assignment.muted})}>AUX</button><button className={assignment.kind==="signal"?"chosen":""} onClick={()=>replace({kind:"signal",level:assignment.level,pan:assignment.pan,muted:assignment.muted})}>SIG GEN</button><button className={assignment.kind==="unassigned"?"chosen":""} onClick={()=>replace({kind:"unassigned",level:assignment.level,pan:assignment.pan,muted:assignment.muted})}>OFF</button></div>
        {assignment.kind==="input"&&<><label htmlFor="source">Source channel</label><select id="source" value={assignment.source} onChange={e=>replace({...assignment,source:Number(e.target.value)})}>{Array.from({length:40},(_,i)=><option key={i} value={i+1}>{inputName(i+1,sourceLabels)}</option>)}</select></>}
        {assignment.kind!=="unassigned"&&<MixControls title={assignment.kind==="group"?"Group level":"Key mix"} level={assignment.level} pan={assignment.pan} muted={assignment.muted} showPan={assignment.kind!=="group"} onChange={updateMix}/>} {assignment.kind==="unassigned"&&<p className="special-source">This key is unassigned.</p>}
        {assignment.kind==="group"&&<div className="group-editor"><div className="group-label"><span className="field-label">Group members</span><span>{members.length}/40</span></div><div className="source-grid">{Array.from({length:40},(_,i)=>i+1).map(source=><button key={source} title={inputName(source,sourceLabels)} aria-label={inputName(source,sourceLabels)} className={`${memberSet.has(source)?"included":""} ${memberSource===source?"focused":""}`} onClick={()=>memberSet.has(source)?setMemberSource(source):updateMember(source,{})}>{source}</button>)}</div>{activeMember&&<div className="member-panel"><div className="member-heading"><strong>{inputName(activeMember.source,sourceLabels)}</strong><button onClick={removeMember}>REMOVE</button></div><MixControls title="In-group mix" level={activeMember.level} pan={activeMember.pan} muted={false} onChange={v=>updateMember(activeMember.source,v)}/></div>}</div>}
        <div className="format-note"><span>FILE SAFETY</span><strong>{preset.formatStatus==="template"?"READY FROM VALIDATED TEMPLATE":"IMPORTED FILE READY"}</strong><p>{preset.formatStatus==="template"?"Build from scratch and export a hardware-compatible 4 KB preset.":"Unknown device bytes are preserved while your edited settings are written."}</p>{configuration&&<button onClick={exportPreset}>EXPORT THIS MIX</button>}<button onClick={()=>saveBlob(exportEditorDraft(preset),`${safePresetName(preset.name)||"PRESET"}.me1draft.json`)}>SAVE EDITOR DRAFT</button></div>
      </>}</aside></div></section><footer><span>LOCAL ONLY · YOUR FILES NEVER LEAVE THIS BROWSER</span><span>HARDWARE-CALIBRATED BUILD 04</span></footer></main>;
}

function ConfigurationManager({configuration,onPresetOneNameChange,onExportNameChange,onEditSlot,onSourceNames,sourceCount}:{configuration:Configuration;onPresetOneNameChange:(name:string)=>void;onExportNameChange:(name:string)=>void;onEditSlot:(presetNumber:number)=>void;onSourceNames:()=>void;sourceCount:number}) { const saved=1+configuration.slots.filter(Boolean).length; return <><div className="inspector-title"><div><p className="eyebrow">CONFIGURATION</p><h2>{saved}<small>/16</small></h2></div><div className="inspector-actions"><button className="active-pill" onClick={onSourceNames}>SOURCE NAMES</button><span className="active-pill">RECALL MIXES</span></div></div><div className="configuration-manager"><button className="source-set-status" onClick={onSourceNames}><span>SOURCE NAME SET</span><strong>{sourceCount?`${sourceCount} INPUTS NAMED`:"NOT LOADED"}</strong></button><label htmlFor="preset-one-name">Preset 1 / configuration name</label><div className="preset-name"><input id="preset-one-name" aria-label="Preset 1 and configuration name" maxLength={8} value={configuration.name} onChange={e=>onPresetOneNameChange(e.target.value)}/><span>{configuration.name.length}/8</span></div><p className="name-help">The ME-1 uses this name for both Preset 1 and the configuration shown on its screen.</p><label htmlFor="export-name">Export file name</label><div className="compact-name"><input id="export-name" aria-label="Export file name" maxLength={8} value={configuration.exportName} onChange={e=>onExportNameChange(e.target.value)}/><span>{configuration.exportName.length}/8</span></div><p className="name-help">This is only the computer/USB filename.</p><div className="slot-manager-heading"><div><span className="field-label">ME-1 presets</span><p>Preset 1 is the current mix. Build or edit Presets 2–16 below.</p></div><strong>{saved} SAVED</strong></div><div className="slot-manager"><button className="filled" onClick={()=>onEditSlot(1)} aria-label={`Edit Preset 1, ${configuration.name}`}><b>01</b><span>{configuration.name}</span><em>EDIT</em></button>{configuration.slots.map((slot,index)=>{const presetNumber=index+2; return <button key={index} className={slot?"filled":""} onClick={()=>onEditSlot(presetNumber)} aria-label={`${slot?"Edit":"Build"} Preset ${presetNumber}${slot?`, ${slot.name}`:""}`}><b>{String(presetNumber).padStart(2,"0")}</b><span>{slot?.name||"EMPTY"}</span><em>{slot?"EDIT":"BUILD"}</em></button>})}</div></div><div className="format-note config-export-note"><span>READY TO DEPLOY</span><strong>{saved} OF 16 PRESETS SAVED</strong><p>Export one 72 KB configuration containing Presets 1–16.</p></div></> }

function SourceNamesEditor({name,labels,onNameChange,onLabelsChange,onImport,onExport,onBack}:{name:string;labels:string[];onNameChange:(name:string)=>void;onLabelsChange:(labels:string[])=>void;onImport:()=>void;onExport:()=>void;onBack:()=>void}) { const setLabel=(index:number,value:string)=>onLabelsChange(labels.map((label,i)=>i===index?value.slice(0,48):label)); const named=labels.filter(label=>label.trim()).length; return <><div className="inspector-title"><div><p className="eyebrow">SOURCE NAMES</p><h2>{named}<small>/40</small></h2></div><button className="active-pill" onClick={onBack}>DONE</button></div><div className="source-names-editor"><p className="source-names-help">These labels are only used in this editor. Inputs in ME-1 files remain numbered 1–40.</p><label htmlFor="source-set-name">Source name set</label><div className="compact-name"><input id="source-set-name" aria-label="Source name set" value={name} maxLength={32} onChange={e=>onNameChange(e.target.value)}/><span>{name.length}/32</span></div><div className="source-file-actions"><button onClick={onImport}>LOAD SET</button><button onClick={onExport}>SAVE SET</button></div><div className="source-name-list">{labels.map((label,index)=><label key={index}><b>{String(index+1).padStart(2,"0")}</b><input aria-label={`Input ${index+1} source name`} value={label} placeholder={`Input ${index+1}`} onChange={e=>setLabel(index,e.target.value)}/></label>)}</div></div></> }

function DeviceScreen({assignment,displayName,selected,groupView,sourceLabels}:{assignment:Assignment;displayName:string;selected:number;groupView:boolean;sourceLabels:string[]}) {
  if (assignment.kind === "group" && groupView) return <div className="device-screen member-screen"><div className="member-screen-head"><strong>{displayName}</strong><span>GROUP MEMBERS</span></div><div className="oled-member-list" aria-label={`${displayName} group members`}>{assignment.members.length ? assignment.members.map((member,index)=><div className="oled-member" key={member.source}><span className="member-cursor">{index===0?"›":""}</span><b>{inputName(member.source,sourceLabels)}</b><div className="member-level-mini"><i style={{width:`${levelPercent(member.level)}%`}}/></div><em>{panLabel(member.pan)}</em></div>) : <div className="oled-empty">NO MEMBERS</div>}</div><div className="scroll-hint">SCROLL ↕</div></div>;
  const percent=levelPercent(assignment.level);
  return <div className={`device-screen ${assignment.muted?"screen-muted":""}`}><div className="screen-grid"><div className="screen-main"><div className="screen-title"><strong>{displayName}</strong><em>{String(selected+1).padStart(2,"0")}</em></div>{assignment.kind!=="group"&&<div className="screen-pan screen-pan-primary"><div className="screen-label"><span>PAN</span><b>{panLabel(assignment.pan)}</b></div><div className="pan-meter"><i style={{left:`${(assignment.pan+100)/2}%`}}/><span/></div></div>}{assignment.kind==="group"&&<div className="group-screen-note">PRESS GROUP FOR MEMBERS</div>}{assignment.muted&&<div className="screen-mute">MUTED</div>}</div><div className="screen-level-meter" aria-label={`${assignment.kind==="group"?"Group level":"Level"}: ${levelLabel(assignment.level)}`}><div className="vertical-level-track"><span className="vertical-level-label">{assignment.kind==="group"?"GRP":"LEVEL"}</span><i style={{height:`${assignment.muted?3:percent}%`}}/><b className="vertical-nominal"/></div></div></div></div>;
}

function MixControls({title,level,pan,muted,showPan=true,onChange}:{title:string;level:number;pan:number;muted:boolean;showPan?:boolean;onChange:(v:{level?:number;pan?:number;muted?:boolean})=>void}) { const nominalPercent=levelPercent(LEVEL_NOMINAL); return <div className="mix-controls"><div className="group-label"><span className="field-label">{title}</span><button className={`mute-toggle ${muted?"on":""}`} onClick={()=>onChange({muted:!muted})}>{muted?"MUTED":"MUTE"}</button></div><div className="range-row"><span>LEVEL</span><div className="level-control"><input aria-label={`${title} level`} type="range" min="0" max={LEVEL_MAX} step="1" value={level} onChange={e=>onChange({level:Number(e.target.value)})}/><span className="range-nominal" style={{left:`${nominalPercent}%`}}>0</span><div className="range-ends"><span>OFF</span><span>+10</span></div></div><b>{levelLabel(level)}</b></div>{showPan&&<div className="range-row"><span>PAN</span><input aria-label={`${title} pan`} type="range" min="-100" max="100" value={pan} onChange={e=>onChange({pan:Number(e.target.value)})}/><b>{panLabel(pan)}</b></div>}</div>; }
const levelPercent=(level:number)=>Math.round((level/LEVEL_MAX)*1000)/10;
const levelLabel=(level:number)=>level===0?"OFF":level===LEVEL_NOMINAL?"0 dB":level===LEVEL_MAX?"+10 dB":level<LEVEL_NOMINAL?"BELOW 0":"ABOVE 0";
const panLabel=(pan:number)=>Math.abs(pan)<2?"C":pan<0?`L${Math.abs(pan)}`:`R${pan}`;
function MixerKey({index,item,labels,selected,onSelect}:{index:number;item:Assignment;labels:string[];selected:number;onSelect:(i:number)=>void}) { return <button className={`device-key ${selected===index?"active":""} ${item.muted?"muted":""}`} onClick={()=>onSelect(index)} aria-label={`Select key ${index+1}, ${sourceName(item,labels)}`} aria-pressed={selected===index}><span>{index+1}</span><i/></button>; }
