"use client";
import { ChangeEvent, useRef, useState } from "react";
import { Assignment, blankPreset, exportEditorDraft, GroupMember, parseME1, writeME1 } from "./me1-format";

const sourceName = (a: Assignment) => a.kind === "input" ? `IN ${a.source}` : a.kind === "group" ? `GRP ${a.members.length}` : a.kind === "signal" ? "SIG GEN" : a.kind.toUpperCase();
const saveBlob = (blob: Blob, name: string) => { const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); };

const safePresetName = (name: string) => name.toUpperCase().replace(/[^A-Z0-9_]/g, "").slice(0, 8);

export function ME1Editor() {
  const [preset, setPreset] = useState(blankPreset); const [selected, setSelected] = useState(0); const [memberSource, setMemberSource] = useState(1); const [groupView, setGroupView] = useState(false); const [notice, setNotice] = useState("New preset ready · built from the hardware-validated template"); const fileRef = useRef<HTMLInputElement>(null);
  const assignment = preset.assignments[selected]; const keyName = preset.keyNames[selected];
  const members = assignment.kind === "group" ? assignment.members : []; const memberSet = new Set(members.map(m => m.source)); const activeMember = assignment.kind === "group" ? assignment.members.find(m => m.source === memberSource) : undefined;
  const displayName = keyName.mode === "custom" && keyName.customName ? keyName.customName : sourceName(assignment);
  const selectKey = (key:number) => { setSelected(key); setGroupView(false); };
  const replace = (next: Assignment) => setPreset(p => ({ ...p, assignments: p.assignments.map((a,i) => i === selected ? next : a) }));
  const updateMix = (values: Partial<Pick<Assignment,"level"|"pan"|"muted">>) => replace({ ...assignment, ...values } as Assignment);
  const rename = (mode:"console"|"custom", customName=keyName.customName) => setPreset(p => ({ ...p, keyNames:p.keyNames.map((n,i)=>i===selected?{mode,customName}:n) }));
  const updateMember = (source:number, patch:Partial<GroupMember>) => { if (assignment.kind !== "group") return; const exists = assignment.members.find(m=>m.source===source); const member={source,level:50,pan:0,...exists,...patch}; replace({...assignment,members:[...assignment.members.filter(m=>m.source!==source),member].sort((a,b)=>a.source-b.source)}); setMemberSource(source); };
  const removeMember = () => { if (assignment.kind === "group") replace({...assignment,members:assignment.members.filter(m=>m.source!==memberSource)}); };
  const importFile = async (e:ChangeEvent<HTMLInputElement>) => { const file=e.target.files?.[0]; if(!file)return; try { const parsed=parseME1(file.name,new Uint8Array(await file.arrayBuffer())); setPreset(parsed); setSelected(0); setNotice(`${file.name} decoded · ${parsed.sourceFile?.sourceKind === "config" ? "current state from config" : "preset"}`); } catch(err){setNotice(err instanceof Error?err.message:"Could not read that file.");} e.target.value=""; };
  const newPreset = () => { setPreset(blankPreset()); setSelected(0); setMemberSource(1); setGroupView(false); setNotice("New preset ready · choose a name and build your mix"); };
  const exportPreset = () => { try { const name=safePresetName(preset.name)||"PRESET"; const fileName=`${name}.ME1`; const bytes=writeME1({...preset,name}); saveBlob(new Blob([bytes],{type:"application/octet-stream"}),fileName); setNotice(`${fileName} exported · ready for the ME1 USB helper`); } catch(err){setNotice(err instanceof Error?err.message:"Could not export.");} };

  return <main><header className="topbar"><div className="brand"><span className="brand-mark">ME</span><span>PRESET LAB</span></div><div className="file-actions"><input ref={fileRef} type="file" accept=".me1" onChange={importFile} hidden/><button className="ghost" onClick={newPreset}>NEW PRESET</button><button className="ghost" onClick={()=>fileRef.current?.click()}>OPEN .ME1</button><button className="ghost" onClick={()=>saveBlob(exportEditorDraft(preset),`${safePresetName(preset.name)||"PRESET"}.me1draft.json`)}>SAVE DRAFT</button><button className="primary" onClick={exportPreset}>EXPORT .ME1</button></div></header>
    <section className="workspace"><div className="intro"><div><p className="eyebrow">ALLEN &amp; HEATH ME-1</p><h1>Your mixer,<br/>mapped simply.</h1></div><div className="status"><span className="dot"/><span>{notice}</span></div></div><div className="editor-grid">
      <section className="mixer" aria-label="Simplified ME-1 personal mixer"><div className="mixer-top"><div className="knob-block display-only"><span>LOCAL MIC</span><div className="knob small"><i/></div><small>VIEW ONLY</small></div><div className="display-block"><div className="device-brand"><b>ALLEN&amp;HEATH</b><span>ME 1</span></div><DeviceScreen assignment={assignment} displayName={displayName} selected={selected} groupView={groupView}/></div><div className="knob-block display-only"><span>MASTER LEVEL</span><div className="knob small"><i/></div><small>VIEW ONLY</small></div></div>
      <div className="hardware-controls"><div className="hardware-left"><button className="face-button round display-only" disabled>SHIFT</button><span className="face-rule">STORE PRESET</span><button className="face-button display-only" disabled>RECALL</button></div><div className="hardware-center"><span className="face-rule">MENU</span><div><button className={`face-button ${assignment.kind==="group"?"lit group-lit":""}`} disabled={assignment.kind!=="group"} onClick={()=>setGroupView(v=>!v)}>GROUP</button><button className="face-button display-only" disabled>SOLO</button><button className={`face-button mute-face ${assignment.muted?"lit":""}`} onClick={()=>updateMix({muted:!assignment.muted})}>MUTE</button></div></div><div className="hardware-right"><div className="master-control"><span>EXIT MENU</span><button className="face-button display-only" disabled>MASTER</button></div><div className="encoder-block display-only"><div className="knob encoder"><i/></div><b>LEVEL / PAN</b><small>VIEW ONLY</small></div></div></div><div className="select-bank"><div className="select-row">{preset.assignments.slice(0,8).map((item,i)=><MixerKey key={i} index={i} item={item} selected={selected} onSelect={selectKey}/>)}</div><div className="scribble"><span>{String(selected+1).padStart(2,"0")}</span><strong>{displayName}</strong></div><div className="select-row">{preset.assignments.slice(8,16).map((item,i)=><MixerKey key={i+8} index={i+8} item={item} selected={selected} onSelect={selectKey}/>)}</div></div><div className="device-footer"><span>16 ASSIGNABLE KEYS</span><b>ME-1</b><span>40 SOURCES</span></div></section>
      <aside className="inspector"><div className="inspector-title"><div><p className="eyebrow">SELECT KEY</p><h2>{String(selected+1).padStart(2,"0")}</h2></div><span className="active-pill">{preset.formatStatus==="decoded-me1"?"IMPORTED":"NEW"}</span></div>
        <label htmlFor="preset-name">Preset filename</label><div className="preset-name"><input id="preset-name" aria-label="Preset filename" maxLength={8} value={preset.name} placeholder="PRESET" onChange={e=>setPreset(p=>({...p,name:safePresetName(e.target.value)}))}/><span>{preset.name.length}/8</span></div><p className="name-help">Letters, numbers, and underscores only · exports as {(safePresetName(preset.name)||"PRESET")}.ME1</p>
        <span className="field-label">Button name</span><div className="segmented name-mode"><button className={keyName.mode==="console"?"chosen":""} onClick={()=>rename("console")}>CONSOLE</button><button className={keyName.mode==="custom"?"chosen":""} onClick={()=>rename("custom")}>CUSTOM</button></div>{keyName.mode==="custom"&&<div className="custom-name"><input aria-label="Custom button name" maxLength={6} value={keyName.customName} placeholder="6 CHARS" onChange={e=>rename("custom",e.target.value.replace(/[^0-9A-Za-z ]/g,"").slice(0,6))}/><span>{keyName.customName.length}/6</span></div>}
        <span className="field-label">Assignment type</span><div className="segmented assignment-types"><button className={assignment.kind==="input"?"chosen":""} onClick={()=>replace({kind:"input",source:selected+1,level:assignment.level,pan:assignment.pan,muted:assignment.muted})}>INPUT</button><button className={assignment.kind==="group"?"chosen":""} onClick={()=>replace({kind:"group",members:[],level:assignment.level,pan:0,muted:assignment.muted})}>GROUP</button><button className={assignment.kind==="auto"?"chosen":""} onClick={()=>replace({kind:"auto",level:assignment.level,pan:assignment.pan,muted:assignment.muted})}>AUTO</button><button className={assignment.kind==="aux"?"chosen":""} onClick={()=>replace({kind:"aux",level:assignment.level,pan:assignment.pan,muted:assignment.muted})}>AUX</button><button className={assignment.kind==="signal"?"chosen":""} onClick={()=>replace({kind:"signal",level:assignment.level,pan:assignment.pan,muted:assignment.muted})}>SIG GEN</button><button className={assignment.kind==="unassigned"?"chosen":""} onClick={()=>replace({kind:"unassigned",level:assignment.level,pan:assignment.pan,muted:assignment.muted})}>OFF</button></div>
        {assignment.kind==="input"&&<><label htmlFor="source">Source channel</label><select id="source" value={assignment.source} onChange={e=>replace({...assignment,source:Number(e.target.value)})}>{Array.from({length:40},(_,i)=><option key={i} value={i+1}>Input {i+1}</option>)}</select></>}
        {assignment.kind!=="unassigned"&&<MixControls title={assignment.kind==="group"?"Group level":"Key mix"} level={assignment.level} pan={assignment.pan} muted={assignment.muted} showPan={assignment.kind!=="group"} onChange={updateMix}/>} {assignment.kind==="unassigned"&&<p className="special-source">This key is unassigned.</p>}
        {assignment.kind==="group"&&<div className="group-editor"><div className="group-label"><span className="field-label">Group members</span><span>{members.length}/40</span></div><div className="source-grid">{Array.from({length:40},(_,i)=>i+1).map(source=><button key={source} className={`${memberSet.has(source)?"included":""} ${memberSource===source?"focused":""}`} onClick={()=>memberSet.has(source)?setMemberSource(source):updateMember(source,{})}>{source}</button>)}</div>{activeMember&&<div className="member-panel"><div className="member-heading"><strong>INPUT {activeMember.source}</strong><button onClick={removeMember}>REMOVE</button></div><MixControls title="In-group mix" level={activeMember.level} pan={activeMember.pan} muted={false} onChange={v=>updateMember(activeMember.source,v)}/></div>}</div>}
        <div className="format-note"><span>EXPORT STATUS</span><strong>{preset.formatStatus==="template"?"READY FROM VALIDATED TEMPLATE":"IMPORTED FILE READY"}</strong><p>{preset.formatStatus==="template"?"Build from scratch and export a hardware-compatible 4 KB preset.":"Unknown device bytes are preserved while your edited settings are written."}</p></div>
      </aside></div></section><footer><span>LOCAL ONLY · YOUR FILES NEVER LEAVE THIS BROWSER</span><span>BINARY RESEARCH BUILD 03</span></footer></main>;
}

function DeviceScreen({assignment,displayName,selected,groupView}:{assignment:Assignment;displayName:string;selected:number;groupView:boolean}) {
  if (assignment.kind === "group" && groupView) return <div className="device-screen member-screen"><div className="member-screen-head"><strong>{displayName}</strong><span>GROUP MEMBERS</span></div><div className="oled-member-list" aria-label={`${displayName} group members`}>{assignment.members.length ? assignment.members.map((member,index)=><div className="oled-member" key={member.source}><span className="member-cursor">{index===0?"›":""}</span><b>Input {String(member.source).padStart(2,"0")}</b><div className="member-level-mini"><i style={{width:`${member.level}%`}}/></div><em>{panLabel(member.pan)}</em></div>) : <div className="oled-empty">NO MEMBERS</div>}</div><div className="scroll-hint">SCROLL ↕</div></div>;
  return <div className={`device-screen ${assignment.muted?"screen-muted":""}`}><div className="screen-grid"><div className="screen-main"><div className="screen-title"><strong>{displayName}</strong><em>{String(selected+1).padStart(2,"0")}</em></div><div className="screen-level"><div className="screen-label"><span>{assignment.kind==="group"?"GROUP LEVEL":"LEVEL"}</span><b>{assignment.level}%</b></div><div className="level-track"><i style={{width:`${assignment.level}%`}}/></div></div>{assignment.kind!=="group"&&<div className="screen-pan"><div className="screen-label"><span>PAN</span><b>{panLabel(assignment.pan)}</b></div><div className="pan-track"><i style={{left:`${(assignment.pan+100)/2}%`}}/><span/></div></div>}{assignment.kind==="group"&&<div className="group-screen-note">PRESS GROUP FOR MEMBERS</div>}{assignment.muted&&<div className="screen-mute">MUTED</div>}</div><div className="screen-meters" aria-hidden="true"><div><i style={{height:`${assignment.muted?3:Math.max(8,assignment.level*.82)}%`}}/></div><div><i style={{height:`${assignment.muted?3:Math.max(8,assignment.level)}%`}}/></div><small>L&nbsp;R</small></div></div></div>;
}

function MixControls({title,level,pan,muted,showPan=true,onChange}:{title:string;level:number;pan:number;muted:boolean;showPan?:boolean;onChange:(v:{level?:number;pan?:number;muted?:boolean})=>void}) { return <div className="mix-controls"><div className="group-label"><span className="field-label">{title}</span><button className={`mute-toggle ${muted?"on":""}`} onClick={()=>onChange({muted:!muted})}>{muted?"MUTED":"MUTE"}</button></div><div className="range-row"><span>LEVEL</span><input aria-label={`${title} level`} type="range" min="0" max="100" step="1" value={level} onChange={e=>onChange({level:Number(e.target.value)})}/><b>{level}%</b></div>{showPan&&<div className="range-row"><span>PAN</span><input aria-label={`${title} pan`} type="range" min="-100" max="100" value={pan} onChange={e=>onChange({pan:Number(e.target.value)})}/><b>{panLabel(pan)}</b></div>}</div>; }
const panLabel=(pan:number)=>Math.abs(pan)<2?"C":pan<0?`L${Math.abs(pan)}`:`R${pan}`;
function MixerKey({index,item,selected,onSelect}:{index:number;item:Assignment;selected:number;onSelect:(i:number)=>void}) { return <button className={`device-key ${selected===index?"active":""} ${item.muted?"muted":""}`} onClick={()=>onSelect(index)} aria-label={`Select key ${index+1}, ${sourceName(item)}`} aria-pressed={selected===index}><span>{index+1}</span><i/></button>; }
